[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
ITensorDocsNext = "701fd796-f527-45da-9a53-2681c1a90c45"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MultiDocumenter = "87ed4bf0-c935-4a67-83c3-2a03bee4197c"

[compat]
Documenter = "1.9"
DocumenterMermaid = "0.2"
ITensorDocsNext = "0.1"
Literate = "2.20.1"
MultiDocumenter = "0.8"

[sources.ITensorDocsNext]
path = ".."
